### ISSUE TITLE
Add support for 'revert' instead of 'throw'

### ISSUE THREAD

**Issue by MeoMix** [etherdelta/smart_contract#1]
Hey there,

It would be nice if you could update the contract to use `revert` instead of `throw`. It would lead to less gas consumption :)

**Comment by ghost** [comment]
Agreed! The only challenge is that the smart contract upgrade will be a
painful procedure. 100,000 addresses withdrawing Ether and any number of
tokens to switch to the new smart contract...

**Comment by wparad** [comment]
@ghost, that will always be a problem with contracts.  Why not let the market decide how to handle this.  Rather than force the upgrade, allow both versions on the website and display the current conversion.  If users want to migrate to a "safer" contract then they will, and if they don't they can keep using the existing one.  Eventually all of them will be on the new one, if it is better.

One way to do this, is to create a special indicator in the UI next to the trade signally it is for a legacy contract, and when clicking that icon will show you a difference summary.

It isn't a good idea to prevent innovation because of difficulty, instead we should work to decrease the difficulty of innovation.  I believe UX redesign is on the etherdelta roadmap 2018Q2, doesn't say if it only for mobile.
